### PR TITLE
feat(common): add a route /info for operator public key

### PR DESCRIPTION
**Pull request by hopeyen**
adding `/info` endpoint back to query operator info

### CODE REVIEW

**Review by aasseman — CHANGES_REQUESTED** [review]
Perhaps could the operator address be stored as a lazy static instead of recomputing it every time?
Otherwise LGTM

**Comment by hopeyen** [comment]
> Perhaps could the operator address be stored as a lazy static instead of recomputing it every time?

Operator address computed once at the initialization stage of IndexerService, and simply returned when it gets queried. I'm not sure storing operator address as lazy_static since it should be computed based on operator mnemonic. Could you explain a bit more please?

**Comment by aasseman** [comment]
Ah yes, you're right, I misread it!

**Review by aasseman — APPROVED** [review]

**Comment by Jannis** [comment]
@hopeyen This PR is incompatible with the `/info` handler of the existing indexer service, which returns an object. Could we fix that and make them compatible?

https://github.com/graphprotocol/indexer/blob/e701da80600e91ae7c89e2ca0962aea40360082e/packages/indexer-service/src/server/operator.ts#L13

**Pull request merged**
