### PR TITLE
migrate diputes from eventuals to tokio::watch

### LINKED ISSUE #333: Drop eventuals in favor of Tokio watch + timers
@Theodus suggested that Eventuals are really hard to debug and we should probably ship a standard solution like the [Gateway currently does](https://github.com/edgeandnode/gateway/blob/main/src/network/service.rs) by using [tokio watch](https://docs.rs/tokio/latest/tokio/sync/watch/index.html).

- [x] #361
- [x] #363
- [x] #364
- [x] #365 
- [x] #440 
- [x] #441

### PR DESCRIPTION
**Pull request by taslimmuhammed**
Fixes #333 
I just changed the disputes, the other files which utilizes this service  is not migrated, so there is error, could you check the code please, on  your approval, I'll change the remaining too

### CODE REVIEW

**Comment by gusinacio** [comment]
Hello, could you rebase your branch?

**Comment by gusinacio** [comment]
This is how I was planning to do, sending `watch::Receiver<T>` over the places over using `Eventual<t>`. 

Great work, you can keep going for the remaining.

**Comment by carlosvdr** [comment]
I do recommend also using interact rebasing to be able to rename the commits ( since we started using release please, try using [conventional commits](03-1234-1234) ) also squashing if there's too much going on
 :)

**Comment by taslimmuhammed** [comment]
Thanks for the review, I'll start migrating the rest too.

**Comment by taslimmuhammed** [comment]
BTW I don't know if I'm doing it right, but I tried rebase several times, but still it shows forked repo is multiple commits ahead[even after my pr is accepted], as of now I reforked the repo for ease [🥲],

**Pull request closed without merging**
