### PR TITLE
Bulk insert of failed receipts using query macro

### LINKED ISSUE #273: [Feat.Req] Bulk insert of failed receipts
**Problem statement**
We have a loop that inserts all the failed receipts, but it's way more efficient if we insert via bulk.

### PR DESCRIPTION
**Pull request by taslimmuhammed**
Fixes #273 
I have tested the query using a local db, not the entire project, if possible please test it on your environment.

### CODE REVIEW

**Comment by gusinacio** [comment]
Hello, could you run a few commands to make our CI happy?

```bash
cargo clippy --all-targets --all-features # for clippy
cargo fmt # for fmt
cargo sqlx prepare --workspace -- --all-targets # for SQL offline mode
```

**Comment by taslimmuhammed** [comment]
Sure, sorry for the trouble, it's my first time contributing to a large project

**Comment by taslimmuhammed** [comment]
Also could you give me a good on how to test the whole project, I have been testing the queries on  a local db in a diff code.

**Comment by gusinacio** [comment]
Hey, no worries I'm here to guide you.

The service has a lot of dependencies and you probably won't be able to get to specific code paths.

We usually create tests using sqlx to check if the code works.

You can get some examples in the end of the file.

**Pull request closed without merging**
