### PR TITLE
refactor: use graphql-client for status monitor

### LINKED ISSUE #421: Use `graphql-client` for status monitor
I didn't know that this was using the older query and not `graphql-client`. Need to update this on a future PR.

_Originally posted by @gusinacio in https://github.com/graphprotocol/indexer-rs/pull/413#discussion_r1821212495_

### PR DESCRIPTION
**Pull request by taslimmuhammed**
Fixes #421

### CODE REVIEW

**Comment by taslimmuhammed** [comment]
Hi, first time dealing with graphql-client, I hope everything's good, if any or full change[😅] required please tell me.

**Review by gusinacio — APPROVED** [review]
LGTM

**Comment by taslimmuhammed** [comment]
well that was truly unexpected😂, BTW thanks alot for the review as always[🫂]

**Comment by gusinacio** [comment]
> well that was truly unexpected😂, BTW thanks alot for the review as always[🫂]

Thank you for the incredible code!

**Pull request merged**
