### PR TITLE
chore: add Edge & Node to copyright headers

### PR DESCRIPTION
**Pull request by hopeyen**
`// Copyright 2023-, GraphOps, and Semiotic Labs.`
-> 
`// Copyright 2023-, Edge & Node, GraphOps, and Semiotic Labs.`

### CODE REVIEW

**Review by Jannis — APPROVED** [review]
Since the order of teams doesn't matter to me, I'm good with this PR. I'd be just as fine with Edge & Node coming last if it matters to GraphOps or Semiotic.

**Comment by hopeyen** [comment]
I figured to do it by alphabetical order because this doesn't matter to me neither 😬 
@aasseman lmk what you think, changes are easy to make

**Review by aasseman — APPROVED** [review]
Works for me! Let's wait for The Graph Foundation's recommendations though.

**Comment by fordN** [comment]
@PedroMD thoughts on this one?

**Comment by PedroMD** [comment]
The Foundation makes no particular recommendation, as there are no defined rules for such a thing yet. 

Alphabetical ordering is neutral, and everyone seems to agree with it. Let's go! :)

**Pull request closed without merging**
